name: Sync Garmin Metrics

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gspread oauth2client garminconnect

      - name: Run automation script
        env:
          GARMIN_TOKENS_JSON: ${{ secrets.GARMIN_TOKENS_JSON }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        run: |
          python garmin_to_sheets.py
